#!/usr/bin/env python

import os
import subprocess
import sys
from typing import List, Optional

# unused: will be called with subprocess
import sigstore

ORIG_DIR = os.path.dirname(os.path.abspath(__file__))
ISSUER = "https://github.com/login/oauth"

def _run(cmd: List[str]):
    if os.environ.get('DEBUG'):
        subprocess.run(cmd, check=True)
    else:
        subprocess.run(cmd, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, check=True)

def _sign(version: str, dist_dir: str) -> Optional[str]:
    # TODO better version check
    artifacts = [f for f in os.listdir(dist_dir) if version in f]
    if len(artifacts) !=2:
        return f"Expected 2 artifacts for {version}, found {artifacts}"

    cmd = ["python3", "-m", "sigstore", "sign"]
    for artifact in artifacts:
        cmd.append(f"{dist_dir}/{artifact}")
    print("Signing (please login to sigstore with GitHub)...")
    _run(cmd)
    for artifact in artifacts:
        crt = f"{ORIG_DIR}/signatures/{artifact}.crt"
        sig = f"{ORIG_DIR}/signatures/{artifact}.sig"
        os.replace(f"{dist_dir}/{artifact}.sig", sig)
        os.replace(f"{dist_dir}/{artifact}.crt", crt)
        print(f"Signed {artifact}")

    print(f"✅ Signed release {version}")

def _verify(version: str, dist_dir: str, identity: str) -> Optional[str]:
    # TODO better version check
    artifacts = [f for f in os.listdir(dist_dir) if version in f]
    if len(artifacts) !=2:
        return f"Expected 2 artifacts for {version}, found {artifacts}"

    base_cmd = ["python3", "-m", "sigstore", "verify", "--cert-oidc-issuer", ISSUER]
    try:
        for artifact in artifacts:
            crt = f"{ORIG_DIR}/signatures/{artifact}.crt"
            sig = f"{ORIG_DIR}/signatures/{artifact}.sig"
            if (not os.path.exists(crt) or not os.path.exists(sig)):
                return f"Could not find sig or cert for {artifact}"

            cmd = base_cmd + [
                "--cert-email", identity,
                "--certificate", crt,
                "--signature", sig,
                f"{dist_dir}/{artifact}"
            ]
            _run(cmd)
            print(f"{artifact} signed by {identity}")
    except subprocess.CalledProcessError:
        return f"No valid signatures found for {identity}"

    # All artifacts verified succesfully by this identity
    print (f"✅ {version} release artifacts signed by {identity}")

def main(args: List[str]) -> Optional[str]:
    if args[0] == "sign" and len(args) == 2:
        return _sign(args[1], f"{ORIG_DIR}/dist/")
    elif args[0] == "verify" and len(args) == 3:
        return _verify(args[1], f"{ORIG_DIR}/dist/", args[2])
    else:
        return f"Invalid arguments: expecting 'sign <version>' or 'verify <version> <email>'"

if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))